
# Network Settings
# ------- --------

# Name: systemerp
# Subnet: 172.11.0.0/16
# Command: docker network create --driver=bridge --subnet=172.11.1.0/16  systemerp

# Project: 172.11.1.0/24. Range: 172.11.2.0 ~ 172.11.2.255

version: '3'

services:
  nginx:
    container_name: erp_nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8081:443"
    volumes:
      - ./:/var/www
    networks:
      trackingnetwork:
        ipv4_address: 172.11.1.1
    links:
      - app

  app:
    container_name: erp_app
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/app/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - postgres
      - beanstalkd
      - redis
    environment:
      - "APP_NAME=${APP_NAME}"
      - "APP_ENV=${APP_ENV}"
      - "APP_DEBUG=${APP_DEBUG}"
      - "APP_KEY=${APP_KEY}"
      - "DB_CONNECTION=${DB_CONNECTION}"
      - "DB_HOST=${DB_HOST}"
      - "DB_PORT=${DB_PORT}"
      - "DB_DATABASE=${DB_DATABASE}"
      - "DB_USERNAME=${DB_USERNAME}"
      - "DB_PASSWORD=${DB_PASSWORD}"
      - "CACHE_DRIVER=${CACHE_DRIVER}"
      - "QUEUE_DRIVER=${QUEUE_DRIVER}"
      - "REDIS_HOST=${REDIS_HOST}"
      - "REDIS_PASSWORD=${REDIS_PASSWORD}"
      - "REDIS_PORT=${REDIS_PORT}"
    networks:
      trackingnetwork:
        ipv4_address: 172.11.1.2

  redis:
    container_name: erp_redis
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - ./docker/data/redis:/data
    networks:
      trackingnetwork:
        ipv4_address: 172.11.1.3

  beanstalkd:
    container_name: erp_beanstalkd
    build:
      context: ./docker/beanstalkd
      dockerfile: Dockerfile
    ports:
      - "11301:11300"
    networks:
      trackingnetwork:
        ipv4_address: 172.11.1.4

  postgres:
    image: postgres:12.10
    container_name: erp_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: resoft
      POSTGRES_USER: resoft
      POSTGRES_PASSWORD: secret1

    volumes:

      - ./docker/data/postgres:/data/postgres
    networks:
      trackingnetwork:
        ipv4_address: 172.11.1.5
  mailhog:
      image: mailhog/mailhog:latest
      container_name: erp_mailhog
      ports:
          - 1026:1025
          - 8026:8025
      networks:
          trackingnetwork:
              ipv4_address: 172.11.1.6

networks:
  trackingnetwork:
    external:
      name: systemerp
