
# Network Settings
# ------- --------

# Name: systemerp
# Subnet: 172.11.0.0/16
# Command: docker network create --driver=bridge --subnet=172.11.1.0/16  systemerp

# Project: 172.11.1.0/24. Range: 172.11.2.0 ~ 172.11.2.255

version: '3'

services:
  nginx:
    container_name: erp_nginx
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8081:443"
    volumes:
      - ./:/var/www
    networks:
      systemerp:
        ipv4_address: 172.11.1.1
    links:
      - app

  app:
    container_name: erp_app
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/app/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    depends_on:
      - postgres
    networks:
      systemerp:
        ipv4_address: 172.11.1.2

  postgres:
    image: postgres:12.10
    container_name: erp_postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgresq_data:/data/postgres
    networks:
      systemerp:
        ipv4_address: 172.11.1.3
        
  mailhog:
      image: mailhog/mailhog:latest
      container_name: erp_mailhog
      ports:
          - 1026:1025
          - 8026:8025
      networks:
          systemerp:
              ipv4_address: 172.11.1.4

networks:
  systemerp:
    external:
      name: systemerp

volumes:
  postgresq_data: